name: Build and Deploy React App to CloudFront
on:
    push:
      branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
     BUCKET: <bucket-name>
     DIST: build
     REGION: ap-south-1
     DIST_ID: <ID>