name: Build and Deploy React App to CloudFront
on:
    push:
      branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
     BUCKET: <bucket-name>
     DIST: build
     REGION: ap-south-1
     DIST_ID: <ID>

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       